### PR TITLE
Solve issue Move Engine to new name space #303

### PR DESCRIPTION
**Pull request by matsduf**
The changes in this PR only changes the name space from Zonemaster to Zonemaster::Engine. Each commit is a step that has been verified to pass all the unit tests. The final commit is an update of some documents.

### CODE REVIEW

**Comment by matsduf** [comment]
Travis checks fail because building is depending on binary "msgfmt". See issues #223 and #224.

**Comment by pawal** [comment]
Are you preparing for a major release?

**Comment by matsduf** [comment]
@pawal, changing name space will be a major release.

**Comment by matsduf** [comment]
I have created an identical PR in my fork, and then there is no issue with Travis. See https://github.com/matsduf/zonemaster-engine/pull/4

**Comment by matsduf** [comment]
@vlevigneron, in the PR I have not incremented any version numbers. Should I have done that? What is the principle?

**Comment by vlevigneron** [comment]
@matsduf The principle is, each time you modify a file, even just a comment, you should increase version number. So yes, you should increase all of them.

**Comment by matsduf** [comment]
@vlevigneron: Only .pm files have version number, so only those could be updated. I will do that.

**Comment by matsduf** [comment]
I did a rebase of the branch from which the PR is created to these commits above the commits added to the master branch by PR #305

**Pull request merged**
