### PR TITLE
Remove unused internal package version numbers

### PR DESCRIPTION
**Pull request by mattias-p**

### CODE REVIEW

**Comment by matsduf** [comment]
@vlevigneron, we have a model for incrementing the version on the main module and the component. What is the model for version number on the individual modules? Do you just use the version number to keep track of what modules that have been updated?

I cannot see any harm of the version numbers, but it we need some explicit model.

**Comment by mattias-p** [comment]
@vlevigneron, thanks for reviewing, and sorry I didn't know that. But I agree with @matsduf. Can you say something about how they're useful so we don't break that use case in the future just because we didn't understand it?

**Comment by vlevigneron** [comment]
le 25 oct., matsduf a ?crit :
> @vlevigneron, we have a model for incrementing the version on the main module and the component. What is the model for version number on the individual modules? Do you just use the version number to keep track of what modules that have been updated?
> 
> I cannot see any harm of the version numbers, but it we need some explicit model.
> 

Yes, I understand that for the packaging, we take only the version
number of the main module. But when I fix issues on different
branches/repositories which are not all on the same version of the 
code, it's the fastest way for me to know if the modules are the same,
which one has the most recent features... And just, to know if a
specific module has changed between differents versions of the main
module...

If it breaks nothing, I would prefer to keep this granularity to track
module changes individually.

> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/pull/326#issuecomment-339394010

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by vlevigneron** [comment]
le 25 oct., Mattias Päivärinta a ?crit :
> @vlevigneron, thanks for reviewing, and sorry I didn't know that. But I agree with @matsduf. Can you say something about how they're useful so we don't break that use case in the future just because we didn't understand it?
> 

Is the reply I gave to Mats enough for you or do you need more details ?

> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dotse/zonemaster-engine/pull/326#issuecomment-339567498

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@nic.fr

**Comment by sandoche2k** [comment]
@mattias please respond to Vincent, if you need more details.

**Comment by mattias-p** [comment]
I don't see how the submodule version numbers would break anything in a technical sense. If the submodule version numbers don't follow our [component versioning principle](https://github.com/dotse/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md) they might cause user confusion. So if we keep the submodule version numbers, we should update our [component versioning principle](https://github.com/dotse/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md) to clarify for user what to expect from these version numbers as well.

On the other hand I think git is a better solution to the stated problem.

So what do you prefer @vlevigneron?
1) Maintaining submodule version numbers according to our [component versioning principle](https://github.com/dotse/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md), or
2) Update our [component versioning principle](https://github.com/dotse/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md) to clarify versioning of submodules, or
3) Remove submodule version numbers and track of changes using git?

I'm okay with any one of these three options.

**Comment by matsduf** [comment]
If we decide to have versions on all perl modules (not just the main one) I need to know what I should do if I create a PR changing such a perl module. Should I also update the version number? If so, what is the versioning model? I need to know what version to set on the module.

**Comment by sandoche2k** [comment]
I will move the discussion for 2018.1

**Comment by mattias-p** [comment]
Won't fix. This evolved into dotse/zonemaster#535 instead.

**Pull request closed without merging**
