### PR TITLE
- fixes dotse/zonemaster-engine#384

### PR DESCRIPTION
**Pull request by vlevigneron**

### CODE REVIEW

**Comment by matsduf** [comment]
@vlevigneron, what issue will this PR solve?

**Comment by vlevigneron** [comment]
@matsduf It fixes output of error messages where we could find strings like "at /usr/local/share/perl/5.22.1/Zonemaster/Engine/Nameserver.pm line 301, <DATA> line 20.".

**Comment by matsduf** [comment]
Tested and found to give better message, i.e. solves #384.

**Comment by sandoche2k** [comment]
@vlevigneron close and merge?

**Comment by sandoche2k** [comment]
@matsduf i am merging this PR. If approved close https://github.com/dotse/zonemaster-engine/issues/384

**Pull request merged**
