### PR TITLE
fixes dotse/zonemaster-engine#431

### PR DESCRIPTION
**Pull request by mtoma**

### CODE REVIEW

**Comment by pawal** [comment]
You want to remove these files from the manifest:

+Zonemaster-v1.0.6.tar.gz
+Zonemaster-v1.0.7.tar.gz

**Comment by pawal** [comment]
And all of the files here: inc/Module/Install*

Is there a reason to add .travis.yml?

**Comment by mtoma** [comment]
Why should the MANIFEST file itself be in the repo?
It can be regenerated by the make manifest target before release.

**Comment by mtoma** [comment]
Whe shoumd probably use a MANIFEST.SKIP file instead.

**Comment by mtoma** [comment]
This worked for me using the MANIFEST.SKIP file
rm -rf inc/ && perl Makefile.PL && make manifest && make dist

**Pull request merged**
