### PR TITLE
- Fixes dotse/zonemaster#439

### PR DESCRIPTION
**Pull request by vlevigneron**
Fixes dotse/zonemaster-engine#148

Need swedish translation for messages with tag:
CONSISTENCY:EXTRA_ADDRESS_PARENT
CONSISTENCY:EXTRA_ADDRESS_CHILD
CONSISTENCY:TOTAL_ADDRESS_MISMATCH
CONSISTENCY:ADDRESSES_MATCH

### CODE REVIEW

**Comment by matsduf** [comment]
I expected to find those in the English .po, but they are not there. Where do I find the msgids for those messages?

**Comment by vlevigneron** [comment]
Are you sure, I see them in en.po, fr.po, ... in share directory.

**Comment by matsduf** [comment]
I am in master branch. Should get some other branch?

**Comment by vlevigneron** [comment]
Fixes dotse/zonemaster-engine#148

**Pull request merged**
