### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by haarbo**
For version 1.1.0

### CODE REVIEW

**Comment by sandoche2k** [comment]
@matsduf unless and otherwise you know Danish, i would let you to approve and close the pull request

**Comment by matsduf** [comment]
I do know and speak Danish, and I plan to review. 

The other "problem" is that the PR is against the master branch, so we have to ask @haarbo to create the PR against the develop branch instead.

**Comment by sandoche2k** [comment]
@haarbo thanks for your input to ZM. Sorry for the inconvenience, can you make the PR to the develop branch.

**Comment by haarbo** [comment]
Adding pull request to develop instead.

**Comment by haarbo** [comment]
Had a little bit of trouble making the PR to develop. Hopefully it is okay by now. Otherwise, please let me know.

**Comment by matsduf** [comment]
@haarbo, the new PR looks fine. I will review.

**Pull request closed without merging**
